//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class WorkTask
    {
        public System.Guid Id { get; set; }

        [DisplayName("Task Name")]
        [Required(ErrorMessage = "Please Input Task Name")]
        public string TaskName { get; set; }
        [DisplayName("Task Description")]
        [Required(ErrorMessage = "Please Input Task Description")]
        public string TaskDescription { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        [DisplayName("Task Due Date")]
        [Required(ErrorMessage = "Please Input Task Due Date")]
        public Nullable<System.DateTime> TaskDueDate { get; set; }
        public Nullable<System.DateTime> TaskCreatedDate { get; set; }
        public string TaskCreatedBy { get; set; }
        public Nullable<System.DateTime> TaskModifiedDate { get; set; }
        public string TaskModifiedBy { get; set; }
        [DisplayName("Task Status")]
        public string TaskStatus { get; set; }
        [DisplayName("Task Priority")]
        [Required(ErrorMessage = "Please Select one of Priority Level")]
        public string TaskPriority { get; set; }
    }
}
